apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    department: engineering
    app: nginx
spec:
  containers:
  - name: nginx
    image: us-central1-docker.pkg.dev/johnwhitaker-sstp-515a745d/source-to-prod-demo/nginx:123
    imagePullPolicy: Always
    ports:
    - containerPort: 80
